### ISSUE TITLE
Doesn't work with spring boot and embedded tomcat

### ISSUE THREAD

**Issue by 1azyman** [webjars/webjars-locator#104]
Accessing http://localhost:8080/wro/test.js resource ends with exception:

`
...another stack...
Caused by: java.nio.file.FileSystemNotFoundException: Provider "war" not installed
        at java.nio.file.Paths.get(Paths.java:147) ~[na:1.8.0_144]
        at org.webjars.urlprotocols.JarUrlProtocolHandler.isArchive(JarUrlProtocolHandler.java:88) ~[webjars-locator-core-0.32.jar!/:na]
        at org.webjars.urlprotocols.JarUrlProtocolHandler.getSegments(JarUrlProtocolHandler.java:74) ~[webjars-locator-core-0.32.jar!/:na]
        at org.webjars.urlprotocols.JarUrlProtocolHandler.getAssetPaths(JarUrlProtocolHandler.java:31) ~[webjars-locator-core-0.32.jar!/:na]
        at org.webjars.WebJarAssetLocator.getAssetPaths(WebJarAssetLocator.java:91) ~[webjars-locator-core-0.32.jar!/:na]
        at org.webjars.WebJarAssetLocator.getFullPathIndex(WebJarAssetLocator.java:121) ~[webjars-locator-core-0.32.jar!/:na]
        at ro.isdc.wro.extensions.locator.WebjarUriLocator.newWebJarAssetLocator(WebjarUriLocator.java:52) ~[wro4j-extensions-1.8.0.jar!/:1.8.0]
        at ro.isdc.wro.extensions.locator.WebjarUriLocator.<init>(WebjarUriLocator.java:44) ~[wro4j-extensions-1.8.0.jar!/:1.8.0]
        at ro.isdc.wro.extensions.locator.support.DefaultLocatorProvider.provideLocators(DefaultLocatorProvider.java:26) ~[wro4j-extensions-1.8.0.jar!/:1.8.0]
        at ro.isdc.wro.extensions.support.spi.DefaultConfigurableProvider.provideLocators(DefaultConfigurableProvider.java:60) ~[wro4j-extensions-1.8.0.jar!/:1.8.0]
        at ro.isdc.wro.model.resource.locator.factory.DefaultUriLocatorFactory.<init>(DefaultUriLocatorFactory.java:30) ~[wro4j-core-1.8.0.jar!/:1.8.0]
        at ro.isdc.wro.manager.WroManager$Builder.<init>(WroManager.java:333) ~[wro4j-core-1.8.0.jar!/:1.8.0]
        at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:77) ~[wro4j-core-1.8.0.jar!/:1.8.0]
        at ro.isdc.wro.manager.factory.BaseWroManagerFactory$1.initialize(BaseWroManagerFactory.java:74) ~[wro4j-core-1.8.0.jar!/:1.8.0]
`

The problem is that `WebJarAssetLocator.listParentURLsWithResource `on line 84 will get classloader `TomcatEmbeddedWebappClassLoader` classloader as a parameter, via `Thread.currentThread().getContextClassLoader()`. That classloader will create two URLs for each jar like this:

`jar:war:file:/demo/target/demo-0.0.1-SNAPSHOT.war*/WEB-INF/lib/less-1.3.3.jar!/META-INF/resources/webjars/
jar:file:/demo/target/demo-0.0.1-SNAPSHOT.war!/WEB-INF/lib/less-1.3.3.jar!/META-INF/resources/webjars`

Problem is that jar:war:file with * in there fails later on with exception mentioned in the beginnig.
If I try to use just spring boot loader, e.g. `LaunchedURLClassLoader`, just a simple test in debugger:

`listParentURLsWithResource(new ClassLoader[]{DemoApplication.class.getClassLoader()}, WEBJARS_PATH_PREFIX)`

it will return only list of 

`jar:file:<SOMETHING>`

Demo project is available here: https://github.com/1azyman/webjars-locator-fail

Is there a way to get around this?

**Comment by jamesward** [comment]
Thanks for reporting.  Looks like the jar protocol handler doesn't work with this.  Here is the code:
https://github.com/webjars/webjars-locator-core/blob/master/src/main/java/org/webjars/urlprotocols/JarUrlProtocolHandler.java

Note this is actually in a different repo:
https://github.com/webjars/webjars-locator-core

So that is where we will fix it.  Can you upload your jar so we can create a unit test for this?

**Comment by 1azyman** [comment]
War creatd by demo project is available here: https://files.fm/u/s8puuudd

**Comment by jamesward** [comment]
This should be fixed by: https://github.com/webjars/webjars-locator-core/commit/8a2ef480ada11fead9677e794e7eecbb5ec4ce77

I'm releasing `0.34` now which will hopefully solve your issue.  If not, can you file a new issue on the https://github.com/webjars/webjars-locator-core repo?

**Comment by 1azyman** [comment]
Thanks.
