### ISSUE TITLE
IllegalStateException: Got deeper than 5 levels while searching ...

### ISSUE THREAD

**Issue by akkie** [webjars/webjars-locator#77]
Hi,

I've currently a problem with the above error when running tests in a Play application. It seems that the webjar locator searches for webjar files in my public project files, and in this files I've a directory structure which has a nesting level deeper than 5.

Here is the complete stack trace:
```
Caused by: java.lang.IllegalStateException: Got deeper than 5 levels while searching /home/christian/projects/my.project/target/web/classes/main/META-INF/resources/webjars
	at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:43)
	at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
	at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
	at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
	at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
	at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
	at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
	at org.webjars.urlprotocols.FileUrlProtocolHandler.listFiles(FileUrlProtocolHandler.java:36)
	at org.webjars.urlprotocols.FileUrlProtocolHandler.getAssetPaths(FileUrlProtocolHandler.java:25)
	at org.webjars.WebJarAssetLocator.getAssetPaths(WebJarAssetLocator.java:80)
	at org.webjars.WebJarAssetLocator.getFullPathIndex(WebJarAssetLocator.java:106)
	at controllers.WebJarAssets.<init>(WebJarAssets.scala:26)
	at controllers.WebJarAssets$.<init>(WebJarAssets.scala:66)
	at controllers.WebJarAssets$.<clinit>(WebJarAssets.scala)
```

The path in which the locator searches, doesn't contain any webjar files. It contains only my public project files. This error occurs only during testing. If I remove the nested directories, then the tests runs without any error.

**Comment by jamesward** [comment]
Well that is odd.  What version of `webjars-locator` are you using?  What is the dir structure in your public dir?

I just created dirs 5 deep in the public dir of a Play app and I'm not having any issues.  So we will probably need a failing unit test here that reproduces the issue.

**Comment by akkie** [comment]
Hi James,

I've pushed an example project to: https://github.com/akkie/webjar-bug

If you run `sbt test` then you should see the issue. It seems that the problem occurs with `sbt-web`. Because if I remove the plugin then the test runs without an error.

Christian

**Comment by jamesward** [comment]
This sounds like an issue with how sbt-web is doing stuff.  Can you file an issue over there? https://github.com/sbt/sbt-web/issues

**Comment by akkie** [comment]
@jamesward https://github.com/sbt/sbt-web/issues/104

**Comment by jamesward** [comment]
Thanks.  I'll leave this issue open in case there turns out to be something we need to fix in `webjars-locator`.

**Comment by jamesward** [comment]
I've bumped the number of levels this can aggregate to 32.  To try it, use `webjars-locator` version `0.23` and `webjars-locator-core` version `0.23`.  I'm not sure why the limit was 5 or why we need a limit.  But until we get some time from @huntc to look further into this, lets just try the brute force method.

**Comment by michaelahlers** [comment]
Faced this exact exception when authoring integration tests, and stumbled upon this ticket. For anyone else who finds this and is still working with Play 2.4, upgrading your WebJars dependency to `"org.webjars" %% "webjars-play" % "2.4.0-2"` should solve this issue.
